import './js/components/dataBase/auth';
import './js/components/burgerMenu';
import './js/common/local_storage';
import './js/components/theme';
import './js/components/dataBase/setDatabase';
import './js/components/dataBase/register';
import './js/components/modal'
import './js/components/authForm'
import './js/components/burgerMenu'
